const DATABASE_SCHEMA = {
	tenants: ['id', 'name', 'external_reference', 'created_at', 'updated_at'],
	issuers: [
		'id',
		'tenant_id',
		'name',
		'contact_email',
		'status',
		'created_at',
		'updated_at',
	],
	issuer_users: [
		'id',
		'tenant_id',
		'issuer_id',
		'email',
		'role',
		'status',
		'created_at',
		'updated_at',
	],
	issuer_api_clients: [
		'id',
		'tenant_id',
		'name',
		'client_id',
		'client_secret',
		'scopes',
		'created_at',
		'updated_at',
	],
	issuer_api_keys: [
		'id',
		'tenant_id',
		'api_client_id',
		'key',
		'status',
		'created_at',
		'updated_at',
	],
	document_types: [
		'id',
		'tenant_id',
		'name',
		'description',
		'created_at',
		'updated_at',
	],
	document_templates: [
		'id',
		'tenant_id',
		'document_type_id',
		'name',
		'schema',
		'fields',
		'created_at',
		'updated_at',
	],
	document_records: [
		'id',
		'tenant_id',
		'document_template_id',
		'external_id',
		'recipient_name',
		'issued_at',
		'hash',
		'status',
		'verification_token',
		'qr_token',
		'metadata',
		'created_at',
		'updated_at',
	],
	verification_tokens: [
		'id',
		'tenant_id',
		'document_record_id',
		'token',
		'expires_at',
		'status',
		'created_at',
		'updated_at',
	],
	storage_connections: [
		'id',
		'tenant_id',
		'provider',
		'connection_data',
		'status',
		'created_at',
		'updated_at',
	],
	blockchain_anchors: [
		'id',
		'tenant_id',
		'document_record_id',
		'anchor_hash',
		'chain',
		'transaction_id',
		'status',
		'created_at',
		'updated_at',
	],
	webhooks: [
		'id',
		'tenant_id',
		'target_url',
		'events',
		'secret',
		'status',
		'created_at',
		'updated_at',
	],
	api_logs: [
		'id',
		'tenant_id',
		'api_client_id',
		'path',
		'method',
		'status',
		'request_body',
		'response_body',
		'created_at',
	],
	audit_logs: [
		'id',
		'tenant_id',
		'issuer_id',
		'user_id',
		'action',
		'target',
		'details',
		'created_at',
	],
};

export { DATABASE_SCHEMA };
