export const useCases = [
	{
		slug: 'universities',
		title: 'Universities',
		sector: 'Education',
		headline: 'Issue diplomas, transcripts, and certificates that can be trusted anywhere.',
		summary:
			'Signatura lets universities publish official academic records with QR verification, encrypted student access, revocation controls, and private blockchain proof.',
		issuer: 'University registrar',
		owner: 'Graduate or student',
		verifier: 'Employer, embassy, or licensing body',
		documents: ['Diplomas', 'Transcripts', 'Enrollment records', 'Good moral certificates'],
		pain: ['Fake diplomas circulate online', 'Manual verification slows hiring', 'PDF copies are easy to alter'],
		benefits: ['Instant QR verification', 'Issuer-controlled revocation', 'Trusted records for local and international use'],
		workflow: ['Registrar issues record', 'Student receives verified copy', 'Verifier scans QR', 'Validity is confirmed at source'],
	},
	{
		slug: 'registrar-systems',
		title: 'Registrar Systems',
		sector: 'Education Operations',
		headline: 'Add a secure verification layer to existing registrar workflows.',
		summary:
			'Signatura can sit beside an existing SIS or registrar platform so document teams can issue records without replacing their current source system.',
		issuer: 'Registrar platform',
		owner: 'Student or alumni account',
		verifier: 'Admissions, HR, or government office',
		documents: ['Transfer credentials', 'Certificates of enrollment', 'TOR requests', 'Clearance records'],
		pain: ['Legacy systems lack public verification', 'Records move through email attachments', 'Status updates are hard to track'],
		benefits: ['API-based issuance', 'Audit trails per document', 'Verification without exposing private student data'],
		workflow: ['Registrar system sends data', 'Hash is anchored privately', 'QR is attached', 'Third party verifies status'],
	},
	{
		slug: 'hr-payroll',
		title: 'HR & Payroll',
		sector: 'Workforce',
		headline: 'Make employment records, payslips, and clearances verifiable by design.',
		summary:
			'HR teams can issue official employee documents that workers can keep, share, and prove without back-and-forth calls to the company.',
		issuer: 'Employer or payroll team',
		owner: 'Employee',
		verifier: 'Bank, landlord, recruiter, or agency',
		documents: ['Certificates of employment', 'Payslips', 'Tax forms', 'Final pay and clearance records'],
		pain: ['COE requests are repetitive', 'Payslips are frequently edited', 'Manual HR checks leak time'],
		benefits: ['Employee-controlled sharing', 'Fast authenticity checks', 'Revocation for outdated records'],
		workflow: ['HR issues document', 'Employee stores record', 'Verifier scans QR', 'Current status is returned'],
	},
	{
		slug: 'government',
		title: 'Government',
		sector: 'Public Sector',
		headline: 'Protect public documents while keeping agencies as the source of truth.',
		summary:
			'Agencies can issue permits, certificates, clearances, and licenses with tamper-evident proof and simple QR checks for citizens and field officers.',
		issuer: 'Government agency',
		owner: 'Citizen, business, or applicant',
		verifier: 'Field officer, employer, or receiving agency',
		documents: ['Permits', 'Clearances', 'Licenses', 'Eligibility certificates'],
		pain: ['Paper records are forged', 'Inter-agency checks take days', 'Field verification needs simple tools'],
		benefits: ['QR checks in the field', 'Agency-controlled validity', 'Privacy-preserving document proof'],
		workflow: ['Agency approves record', 'Citizen receives QR document', 'Officer scans', 'Status and issuer are confirmed'],
	},
	{
		slug: 'e-invoice-systems',
		title: 'e-Invoice Systems',
		sector: 'Finance',
		headline: 'Give invoices and receipts a verifiable digital fingerprint.',
		summary:
			'Signatura can anchor invoice hashes and attach verification metadata so buyers, auditors, and finance teams can detect edited or duplicated records.',
		issuer: 'Merchant or finance platform',
		owner: 'Buyer or account holder',
		verifier: 'Auditor, finance team, or tax reviewer',
		documents: ['Invoices', 'Receipts', 'Credit memos', 'Payment confirmations'],
		pain: ['Invoices are modified after sending', 'Duplicate claims are hard to detect', 'Audit evidence is scattered'],
		benefits: ['Tamper-evident invoice proof', 'Fast audit lookup', 'Source-controlled status changes'],
		workflow: ['Invoice is generated', 'Hash is anchored', 'QR is embedded', 'Auditor confirms integrity'],
	},
	{
		slug: 'medical-records',
		title: 'Medical Records',
		sector: 'Healthcare',
		headline: 'Verify health records without exposing the private medical file.',
		summary:
			'Clinics, hospitals, and labs can issue encrypted records where a verifier can confirm authenticity while sensitive content stays permissioned.',
		issuer: 'Clinic, lab, or hospital',
		owner: 'Patient',
		verifier: 'Employer, school, insurer, or border desk',
		documents: ['Lab results', 'Medical certificates', 'Vaccination records', 'Fit-to-work clearances'],
		pain: ['Medical PDFs are sensitive', 'Certificates are easy to fake', 'Verification must respect privacy'],
		benefits: ['Encrypted access', 'Consent-based sharing', 'Authenticity without public medical data'],
		workflow: ['Provider issues record', 'Patient controls access', 'Verifier scans QR', 'Authenticity is confirmed'],
	},
	{
		slug: 'training-certificates',
		title: 'Training Certificates',
		sector: 'Learning & Development',
		headline: 'Turn course completion into portable, verifiable credentials.',
		summary:
			'Training providers can issue certificates that learners can present anywhere, while verifiers can confirm the provider, course, and status instantly.',
		issuer: 'Training provider',
		owner: 'Learner or participant',
		verifier: 'Employer, school, or compliance team',
		documents: ['Course certificates', 'Seminar attendance', 'Safety training records', 'CPD completions'],
		pain: ['Certificates are copied easily', 'Compliance checks are repetitive', 'Expired training is hard to spot'],
		benefits: ['Expiry-aware verification', 'Trusted learner wallet', 'Provider-branded issuance'],
		workflow: ['Provider completes roster', 'Certificate is issued', 'Learner shares QR', 'Verifier checks status'],
	},
	{
		slug: 'professional-credentials',
		title: 'Professional Credentials',
		sector: 'Licensing',
		headline: 'Make licenses, memberships, and accreditations easy to prove.',
		summary:
			'Boards, associations, and certifying bodies can issue credentials that remain verifiable as membership, license status, or expiry changes.',
		issuer: 'Board or professional association',
		owner: 'Professional member',
		verifier: 'Client, employer, regulator, or public portal',
		documents: ['Licenses', 'Board certificates', 'Membership IDs', 'Accreditation letters'],
		pain: ['Expired licenses remain in circulation', 'Public directories are not enough', 'Manual status checks slow onboarding'],
		benefits: ['Live credential status', 'Revocation and renewal support', 'Proof tied to the issuing body'],
		workflow: ['Board issues credential', 'Member stores proof', 'Verifier scans QR', 'License status is shown'],
	},
];

export function getUseCase(slug) {
	return useCases.find((useCase) => useCase.slug === slug);
}
